travis:
  secure:
    BINSTAR_TOKEN: mX59Tcfc7hV2h+AmFKkRhZDg5uSTI3oCRM1vwslerkBjH555htYFuNB0KeYO6J9a4fXbE+6bHGNn52J71Ag2dz4Zjov538HZq2Sok95uusUvJPZgRGcv2Oh7m0NE+YVVTIYt0B2HSOR6009BkBCOBMeDM9TOJlRxaVemQKD3JALE+0x5ReJfgaDU12CJELOqef1Q0hM0HVMbFu58S+l4Sn7R4md93CYyaPxsYXleLgSTgxeOVGBfU6nrGN/xtj5nDwLTuQBMJHgffOwjeiq3mKNWBMgGlV2ZZnhZL5yE6lOxNPk9NdslYoXRsrmNxfXaf/Sy1PQeED5riDUV9OVupW0XDvTj0uzPM0D/4izRiSThiYaiqIgr3RGHe1Ntcz7L92oDgtP7iaXwJuRdxUFQ+hYK1LXmDY9d7QAtP1ZFrkj3Rm+ZWCUVdten5ZTX2UhYlbGRJrCapmmM/efJI9BIVt8nguxdJnO0sfUnVHVHjpFXEd0ptjW+3qUzUu97ALH0+rCA5DzYbuvIK0PxPxVSMGJ6WpVKoBTJLR/RKD1PlQHE4JngjDfT1jDVnZICrPdyhsomkq7Iy0/hGVDJ7zavxyIih6ZxTkOmk7+b32xSDRjITGXqigzBAWSj2RBjro9RRhFSzx+mSFSLLcsFD7Iukus6Zcmb0qGeen0WzsyzsKE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
