travis:
  secure:
    BINSTAR_TOKEN: GOauaFkY0C8TfByAYg5if8G5S5h714mSD1E8JAQFSAEiQa2ARQYxgvhJH5Viu3KIji+eEb2a3voPsWuTy2tecvrpcHGq+fJVnrRGkV7+Z1GEzUGRR1blqyE2iP4GBM/zL6MzTpTly2IGhytAOrkHW9ZQqJLri3n6hKF8UFnvyM0MXyNhAQXs8chs33rPtpst/C896kj49Ibcn+k2ybtx6ItNxoUlkduqVlgNkyQRj1fvCHIummUeNGa5CYhE346oOlJKv6QeLlcs2DYmPnpVLSlTiBqak30gGQXYlV4Rcx/lKCAlB+3H/EI/5WugA2LAZS8S3hk0xY6FxE7BoyZe+gg11AIUoIixPAmU73Ky2MJVdH9pzeoFTmQHVMdZvbMdfChBOYZRKZPp5fvsVzS0xMVr+s2PnfW7Wc063B26HmMs/4iZDYx0DPv2keoAY2K9FdC1W1Fti5MJde+z1WX/SNoCPkW5x+DNERS/PxlQ0wNwQqbrdWDl5+dr69f8Vxf51nyE8rsk1ktBlBOQUSCCfNA5FW1Si49R+ahvR1j+7N+NhqFcwRoBAXH4q6nxT+3di1of2wNTW880yT/yQBnrziqfG0JRSUPt7xQJkLSz+Fb4/tL/saDmBqzSE1T4t2mmTBcWATM4+q4Mtdno74UjNsbKmCYFK4bzV3MPZfBFAGk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
